language: csharp
solution: FindingImmo.sln
mono: none
dotnet: 2.1.302

install:
 - dotnet restore
 - dotnet tool install --global dotnet-sonarscanner


script:
- export PATH="$PATH:/home/travis/.dotnet/tools"
- dotnet sonarscanner begin /k:"FindingImmo" /d:sonar.organization="t-dambacher-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONAR_TOKEN
- dotnet build
- dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN