language: csharp
solution: FindingImmo.sln
mono: none
dotnet: 2.1.302

install:
 - dotnet restore
 - dotnet tool install --global dotnet-sonarscanner


script:
- export PATH="$PATH:/home/travis/.dotnet/tools"
- $HOME/.dotnet/tools/dotnet-sonarscanner begin /k:"FindingImmo" /d:sonar.organization="t-dambacher-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$SONAR_TOKEN /version:"$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT"
- dotnet build
- $HOME/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login=$SONAR_TOKEN

cache:
directories:
- $HOME/.nuget
- $HOME/.sonar/cache