namespace FindingImmo.Core.Domain.Models
{
    public enum Website : int
    {
        TroisGimmobilier = 1,
        TroisPourcentsPointCom = 2,
        QuatrePourcentsImmobilier = 3,
        Absis = 4,
        AdsImmo = 5,
        AIS = 6,
        AIW = 7,
        AlphaPatrimoine = 8,
        Arp = 9,
        AugusteImmo = 10,
        AutrementImmobilier = 11,
        B2L = 12,
        Baumann = 13,
        Bitz = 14,
        Boistelle = 15,
        CapEstImmo = 16,
        Capifrance = 17,
        Century21 = 18,
        Domial = 19,
        Eurotransactions = 20,
        Fnaim = 21,
        Foncia = 22,
        Groupimmo = 23,
        GuyHoquet = 24,
        Heckmann = 25,
        HertrichEtKern = 26,
        Hrd = 27,
        IEVC = 28,
        IMBS = 29,
        ImmobiliereDeHanau = 30,
        ImmobiliereDesRohan = 31,
        Immobiz = 32,
        ImmoGeyer = 33,
        Immosurmesure = 34,
        ImmoTeam = 35,
        LaChenaieImmobilier = 36,
        Laemmel = 37,
        LaLicorne = 38,
        Logia = 39,
        MapsImmo = 40,
        Mehl = 41,
        Mercor = 42,
        OrpiBrumath = 43,
        PrestigeImmo = 44,
        RueDeLImmobilier = 45,
        Salomon = 46,
        Shorp = 47,
        Siihe = 48,
        SolutionsImmo = 49,
        Solvimmo = 50,
        StephanePlaza = 51,
        Upperside = 52
    }
}
